title: Merhaba, Ben Burak Büyükyüksel
description: > # this means to ignore newlines until "baseurl:"
  Görüntü İşleme ve Derin Öğrenme Teknolojilerine İlgi Duyan Biriyim ve Öğrenmeye Devam Edeceğim.
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Burak Büyükyüksel # add your name
author-img: burak-buyukyuksel.jpg # add your photo
about-author: 
  Hoş Geldiniz,
  </br>
  Derin Öğrenme, Görüntü İşleme ve Blockchain alanlarına ilgi duyuyorum.
  Sürekli öğrenmeye ve öğrendiklerimi paylaşmaya hevesli biriyim.
  </br>
  </br>
  </br>
  <span class="color=red;"> &lt;/ Yazılım Geliştirme Mühendisi &gt;
# add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: bbuyukyuksel # add your Github handle
social-linkedin: buyukyukselburak # add your Linkedin handle
social-instagram: codewithperesthayal
social-email: buyukyukselburak@gmail.com # add your Email address

# Disqus
discus-identifier: buyukyukselburak # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]